name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0' 

      - name: Restore dependencies
        run: dotnet restore App.sln

      - name: Build the project
        run: dotnet build App.sln --configuration Release

      - name: Run tests
        run: dotnet test App.sln --configuration Release
